#!/usr/bin/env node
'use strict';

process.env.NODE_ENV = process.env.NODE_ENV || 'development';

var express = require('express');
var path = require('path');

var config = {
    root : __dirname,
    public: __dirname + '/dist',
    port: 4000
}

// Setup server
var app = express();
var server = require('http').createServer(app);

// view engine setup
app.set('views', path.join(__dirname, 'src/views'));
app.set('view engine', 'jade');

app.use(express.static(config.public));

require('./routes')(app);

// Start server
server.listen(config.port, function(){
    console.log('Root folder\t%s', config.root);
    console.log('Public folder\t%s', config.public);
    console.log('Web server listening on %d, in %s mode',
        config.port,
        app.get('env')
    );
});